
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyapqtyrefkdemhxryvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5YXBxdHlyZWZrZGVtaHhyeXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjM3OTAsImV4cCI6MjA2MzgzOTc5MH0.E-Okftoiz6Le5jOuq6PwF030O0eNIuvBbf2cvF1kVs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});

// Log para debug das requisições
supabase.auth.onAuthStateChange((event, session) => {
  console.log('🔐 Auth state changed:', event);
  if (session) {
    console.log('✅ Sessão ativa:', {
      user_id: session.user.id,
      access_token_length: session.access_token.length,
      expires_at: new Date(session.expires_at! * 1000)
    });
  } else {
    console.log('❌ Nenhuma sessão ativa');
  }
});
